### PR TITLE
Bug fix for connect to take connection parameters

### PR DESCRIPTION
**Pull request by ril3y**
I pushed the wrong code the first time.  Just ignore it.  All I really did was make the .connect() method actually APPLY the parameters passed in :)

### CODE REVIEW

**Comment by WarheadsSE** [comment]
There are unneeded whitespace changes here, that actually break alignment. Otherwise, looks good. IIRC there was some reason I had not done this in the past, so if it is working for you, awesome.

**Comment by ril3y** [comment]
I can't imagine why it would break something applying parameters into this but yes its working.

**Comment by WarheadsSE** [comment]
Would you mind fixing the whitespace?

**Comment by WarheadsSE** [comment]
@ril3y whitespace?

**Comment by ril3y** [comment]
Oh I see.  Sorry let me fix it up.

Thanks.

**Comment by WarheadsSE** [comment]
Fixed with recent merge from #3

**Pull request closed without merging**
